---

#####=== install ===#####

- block:
  - name: package | ruby
    package:
      name: ruby
      state: "{{ install_state }}"

  - name: gem | gems
    gem:
      name: "{{ item }}"
      state: "{{ install_state }}"
      include_doc: no
      user_install: "{{ gem_user_install }}"
    with_items: "{{ gems }}"
  tags:
    - bootstrap
    - install
    - update

- name: include | configure gem user install
  include: configure_gems.yml
  when: gem_user_install == True
